   [build]
     publish = "."
     functions = "netlify/functions"

   [[redirects]]
    from = "/api/scan"
    to = "/.netlify/functions/api"
    status = 200
     from = "."
     to = "."
     status = 200