[build]
  functions = "functions"

[[redirects]]
  from = "/api/scan"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/hibp-check"
  to = "/.netlify/functions/hibp-check"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 